"""Legacy attribute definitions shared between compat shims and AppContext."""

LEGACY_MIRROR_ATTRS: tuple[str, ...] = (
    "map_data",
    "pop_density",
    "land_value_mem",
    "crime_mem",
    "pollution_mem",
    "rate_og_mem",
    "trf_density",
    "total_funds",
    "TotalFunds",
    "city_time",
    "city_tax",
    "res_pop",
    "com_pop",
    "ind_pop",
    "fire_pop",
    "road_total",
    "rail_total",
    "pwrd_z_cnt",
    "un_pwrd_z_cnt",
    "res_z_pop",
    "ComZPop",
    "IndZPop",
    "hosp_pop",
    "church_pop",
    "police_pop",
    "fire_st_pop",
    "stadium_pop",
    "coal_pop",
    "nuclear_pop",
    "port_pop",
    "airport_pop",
    "power_stack_num",
    "total_pop",
    "last_total_pop",
    "message_port",
    "mes_x",
    "mes_y",
    "last_pic_num",
    "last_city_pop",
    "last_category",
    "last_message",
    "have_last_message",
    "mes_num",
    "last_mes_time",
    "sound",
    "AutoGo",
    "AutoGoto",
    "auto_go",
    "auto_goto",
    "AutoBudget",
    "auto_budget",
    "AutoBulldoze",
    "auto_bulldoze",
    "MustUpdateOptions",
    "must_update_options",
    "UserSoundOn",
    "user_sound_on",
    "sim_skips",
    "sim_skip",
    "SimSpeed",
    "sim_speed",
)

LEGACY_ATTRIBUTE_ALIASES: dict[str, tuple[str, ...]] = {
    "total_funds": ("TotalFunds",),
    "sound": ("Sound",),
    "auto_budget": ("AutoBudget",),
    "auto_goto": ("AutoGoto",),
    "auto_go": ("AutoGo",),
    "auto_bulldoze": ("AutoBulldoze",),
    "must_update_options": ("MustUpdateOptions",),
    "user_sound_on": ("UserSoundOn",),
    "sim_speed": ("SimSpeed",),
    "sim_skips": ("sim_skips",),
    "sim_skip": ("sim_skip",),
}
